In [ ]:
import numpy as np

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
x=np.ones(4,dtype=np.int64)
print(x)

[1 1 1 1]


Q2 Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [ ]:
X=np.array([[1,2],[3,4]])
X_mat=np.asmatrix(X)
print(X_mat)

[[1 2]
 [3 4]]


Q3 Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [ ]:
X=np.linspace(3.0,10.0,num=50)
print(X)

[ 3.          3.14285714  3.28571429  3.42857143  3.57142857  3.71428571
  3.85714286  4.          4.14285714  4.28571429  4.42857143  4.57142857
  4.71428571  4.85714286  5.          5.14285714  5.28571429  5.42857143
  5.57142857  5.71428571  5.85714286  6.          6.14285714  6.28571429
  6.42857143  6.57142857  6.71428571  6.85714286  7.          7.14285714
  7.28571429  7.42857143  7.57142857  7.71428571  7.85714286  8.
  8.14285714  8.28571429  8.42857143  8.57142857  8.71428571  8.85714286
  9.          9.14285714  9.28571429  9.42857143  9.57142857  9.71428571
  9.85714286 10.        ]


Q4 Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [ ]:
x=np.array([[1,2,3],[4,5,6]])
X_1D=x.flatten()
print(X_1D)

[1 2 3 4 5 6]


Q5 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
X=np.array([1,2,3,4,5,6,7,8,9])
a=np.array_split(X,4)
b=np.array_split(x,2)
c=np.array_split(x,3)
print(a)
print(b)
print(c)

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]
[array([[1, 2, 3]]), array([[4, 5, 6]])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int64)]


 Q6 Compute the inverse and primary diagnol sum of x=[[1,2],[3,4]]

In [ ]:
x=np.array([[1,3],[3,4]])
x_inv=np.linalg.inv(x)
x_trace=np.trace(x)
print(x_inv)
print(x_trace)

[[-0.8  0.6]
 [ 0.6 -0.2]]
5


Q7 Sort x along the second axis. x = [[1,4],[3,1]]

In [ ]:
x=np.array([[1,4],[3,1]])
x_sort=np.sort(x,axis=1)
print(x_sort)

[[1 4]
 [1 3]]


Q8 Get the indices that would sort x(as above) along the second axis.

In [ ]:
indices=np.argsort(x,axis=1)
print(indices)

[[0 1]
 [1 0]]


Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
from numpy import random
array=random.randint(10,size=(2,5))
xmin,xmax=array.min(),array.max()
index_min,index_max=np.argmin(array,axis=1),np.argmax(array,axis=1)
print(xmin)
print(xmax)
print(index_min)
print(index_max)

0
8
[3 3]
[1 0]


Run the following load command to get the 2-Dim iris dataset. Do the following operations on it.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
print(iris_2d)

Drop rows that contain a missing value. 

In [ ]:
import pandas as pd
df=pd.DataFrame(iris_2d)
df1=df.dropna()
print(df1)

Find the correlation between first two columns.

In [ ]:
print(df[0].corr(df[1]))

-0.10936924995064937


Find the mean,median and standard deviation of column 3.

In [ ]:
mean=df[2].mean()
median=df[2].median()
standard_deviation=df[2].std()
print(mean)
print(median)
print(standard_deviation)

3.7586666666666693
4.35
1.7644204199522617


Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

In [ ]:
sepal_length=iris_2d[:,0].astype('float')
petal_length=iris_2d[:,2].astype('float')
volume =(np.pi*petal_length*(sepal_length**2))/3
print(volume.shape)
print(volume)
volume=volume[:,np.newaxis] # to increase dimension
print(volume.shape) 
print(volume)
#Add the new column
result=np.hstack([iris_2d,volume])
print(result)

(150,)
[ 38.13265163  35.20049849  30.07237208  33.23805027  36.65191429
  51.91167701  31.02218026  39.26990817  28.38324243  37.71481981
  45.80442089  38.60389053  33.77840421  21.29895099  42.27327075
  51.03517266  39.69716477  38.13265163  57.83986235  40.85641246
  51.91167701  40.85641246  22.15870018  46.30393412  45.84212
  41.88790205  41.88790205  42.47433268  39.6427105   37.01215025
  38.60389053  45.80442089  42.47433268  44.34881629  37.71481981
  31.41592654  41.1810437   37.71481981  26.35586797  40.85641246
  34.03392041  27.56747554  26.35586797  41.88790205  51.75145578
  33.77840421  43.58017329  31.02218026  44.12366882  36.65191429
 241.16959604 193.01945264 244.29966952 126.71090369 203.52284408
 153.10551797 195.34737279  82.97260357 209.83325652 110.43326496
  91.62978573 153.10237638 150.79644737 183.14123814 118.22441474
 206.83827152 147.78051842 144.43367505 181.14423241 128.0764493
 174.97414443 155.86488352 203.66002695 183.14123814 184.4408103
 200.710

Run the following loaad command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Find the count of unique species.

In [ ]:
import pandas as pd
df=pd.DataFrame(iris)
species=np.unique(df[4])
print(species)

[b'Iris-setosa' b'Iris-versicolor' b'Iris-virginica']


Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
Less than 3 –> ‘small’
3-5 –> ‘medium’
‘>=5 –> ‘large’

In [ ]:
bin_array=[]
for i in df[2]:
  if float(i) < 3:
    bin_array.append('small')
  if float(i) <=3 and float(i)<5:
    bin_array.append('medium')
  if float(i)>=5:
    bin_array.append('large')
print(np.array(bin_array))

['small' 'medium' 'small' 'medium' 'small' 'medium' 'small' 'medium'
 'small' 'medium' 'small' 'medium' 'small' 'medium' 'small' 'medium'
 'small' 'medium' 'small' 'medium' 'small' 'medium' 'small' 'medium'
 'small' 'medium' 'small' 'medium' 'small' 'medium' 'small' 'medium'
 'small' 'medium' 'small' 'medium' 'small' 'medium' 'small' 'medium'
 'small' 'medium' 'small' 'medium' 'small' 'medium' 'small' 'medium'
 'small' 'medium' 'small' 'medium' 'small' 'medium' 'small' 'medium'
 'small' 'medium' 'small' 'medium' 'small' 'medium' 'small' 'medium'
 'small' 'medium' 'small' 'medium' 'small' 'medium' 'small' 'medium'
 'small' 'medium' 'small' 'medium' 'small' 'medium' 'small' 'medium'
 'small' 'medium' 'small' 'medium' 'small' 'medium' 'small' 'medium'
 'small' 'medium' 'small' 'medium' 'small' 'medium' 'small' 'medium'
 'small' 'medium' 'small' 'medium' 'large' 'large' 'medium' 'large'
 'large' 'large' 'large' 'large' 'large' 'large' 'large' 'large' 'large'
 'large' 'large' 'large' 'large

Find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
value_fq=df[2].mode()
print(value_fq)

0    b'1.5'
dtype: object
